name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Se ejecutará cuando se haga push en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t josedtf/pokeneas-app:latest ./pokeneasAppFinal/Dockerfile

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push josedtf/pokeneas-app:latest
